### ISSUE TITLE
Record some GitMinutes

### ISSUE THREAD

**Issue by tfnico** [git-merge/user-day#3]
If anyone wants to record a little mini-episode for [GitMinutes](http://www.gitminutes.com) during the conference, grab hold of me or send me an email on feedback@gitminutes.com

Here's what I look like _right now_ if you want to find me in the crowd:

![gitminutes-thomas](https://f.cloud.github.com/assets/252063/484486/bbfcdbcc-b8d9-11e2-9510-82bf995b5e83.gif)

I might be fiddling with a couple of microphones at any given time :microphone:

Great topics are, well, anything you are passionate about and involves Git.

**Comment by matthewmccullough** [comment]
Holler at me any time. I'm eager to introduce you to a few more of my GitHub colleagues, such as @brntbeer.

**Comment by tfnico** [comment]
Thanks to everyone who contributed with interviews! I plan to release at least two GitMinutes: GitMerge special episodes in the following weeks. Stay tuned!
