### ISSUE TITLE
teaching git

### ISSUE THREAD

**Issue by gurugray** [git-merge/user-day#4]
I'm some kind of git-trainer in our company :)
For the past year I spent a dozen classes and wrote a little visualization tool for help me in it. Can share my experience of teaching git and I **want** to listen about others experience of it.

**Comment by ben** [comment]
I've done some teaching as well, and a couple of the GitHub trainers are around. It might be worth chatting about the brand-new-user experience, and if there's anything we want to do to optimize it.

**Comment by matthewmccullough** [comment]
@brntbeer and I will be here the whole show, all of the days. Just let us know when we should chat. Super interested in both sharing and listening.

**Comment by gurugray** [comment]
good, I hope my English will be enough for chatting with you guys :)

**Comment by aalbagarcia** [comment]
Hi,

I started to provide git training in september in Spain, altough we officially started with the web in december. I'd love to share with you how it was to teach git to my fellow spanish speaking collegues ;-) and of course to listen to how you do it!!!

**Comment by jherland** [comment]
I've done some git training at both my former and current jobs, as well as a couple of Git talks at meetings/conferences. Interested to hear and share experiences with others.
