### ISSUE TITLE
Recursive submodule checkout

### ISSUE THREAD

**Issue by hvoigt** [git-merge/user-day#6]
Please test, discuss with us how submodules should behave once the become first class citizens.

See Jens branch on github: https://github.com/jlehmann/git-submod-enhancements/commits/recursive_submodule_checkout

and the wiki article:

https://github.com/jlehmann/git-submod-enhancements/wiki/Recursive-submodule-checkout

**Comment by matthewmccullough** [comment]
I'm super keen to listen to this as I would like to think about planning this addition to at least the two primary places we house GitHub Git Training materials:
- http://teach.github.com/presentations
- http://youtube.com/github

**Comment by jlehmann** [comment]
We're sitting at the table next to the sound & video recording guys
